# Generated by Django 4.2.16 on 2024-09-22 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmshop', '0002_alter_article_active_alter_article_changed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('first_name', models.CharField(max_length=300, verbose_name='Vorname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=300, verbose_name='Telefonnummer')),
                ('newsletter', models.BooleanField(blank=True, null=True)),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('order_date', models.DateField(verbose_name='Bestelldatum')),
                ('target_date', models.DateField(verbose_name='Liefer-/Abholdatum')),
                ('customer', models.ForeignKey(help_text='Kunde', on_delete=django.db.models.deletion.CASCADE, to='farmshop.customer', verbose_name='Kunde')),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('title', models.CharField(max_length=300, verbose_name='Artikelbezeichnung')),
                ('description', models.CharField(max_length=4096, verbose_name='Artikelbeschreibung')),
                ('orderable', models.BooleanField(help_text='Packung ist bestellbar', verbose_name='Bestellbar')),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('title', models.CharField(max_length=300, verbose_name='Warenlager')),
                ('description', models.CharField(max_length=4096, verbose_name='Warenlagerbeschreibung')),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('units', models.IntegerField(verbose_name='Einheiten')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Packungspreis')),
                ('production_date', models.DateField(verbose_name='Produktionsdatum')),
                ('expiry_date', models.DateField(verbose_name='Haltbarkeitsdatum')),
                ('orderable', models.BooleanField(help_text='Packung ist bestellbar', verbose_name='Bestellbar')),
                ('article', models.ForeignKey(help_text='Artikel', on_delete=django.db.models.deletion.CASCADE, to='farmshop.article', verbose_name='Artikel')),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(help_text='Packung', on_delete=django.db.models.deletion.CASCADE, to='farmshop.package', verbose_name='Packung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('amount', models.IntegerField(verbose_name='Menge')),
                ('order', models.ForeignKey(help_text='Bestellung', on_delete=django.db.models.deletion.CASCADE, to='farmshop.order', verbose_name='Bestellung')),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(help_text='Packung', on_delete=django.db.models.deletion.CASCADE, to='farmshop.package', verbose_name='Packung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('units', models.IntegerField(verbose_name='Einheiten')),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(help_text='Packung', on_delete=django.db.models.deletion.CASCADE, to='farmshop.package', verbose_name='Packung')),
                ('warehouse', models.ForeignKey(help_text='Lagerort', on_delete=django.db.models.deletion.CASCADE, to='farmshop.warehouse', verbose_name='Lagerort')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
