# Generated by Django 4.2.16 on 2024-09-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0003_customer_order_package_warehouse_packagecontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagecontent',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='packagecontent',
            name='price',
        ),
        migrations.RemoveField(
            model_name='packagecontent',
            name='production_date',
        ),
        migrations.AddField(
            model_name='package',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Haltbarkeitsdatum'),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Packungspreis'),
        ),
        migrations.AddField(
            model_name='package',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Produktionsdatum'),
        ),
    ]
