# Generated by Django 4.2.16 on 2024-09-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0004_remove_packagecontent_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='article',
            field=models.ForeignKey(help_text='Artikel', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.article', verbose_name='Artikel'),
        ),
        migrations.AddField(
            model_name='package',
            name='units',
            field=models.IntegerField(null=True, verbose_name='Einheiten'),
        ),
        migrations.DeleteModel(
            name='PackageContent',
        ),
    ]
