# Generated by Django 4.2.16 on 2024-09-22 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmshop', '0005_package_article_package_units_delete_packagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('title', models.CharField(max_length=300, verbose_name='Hofladen')),
                ('description', models.CharField(max_length=4096, verbose_name='Beschreibung Hofladen')),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='farm_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.farmshop'),
        ),
        migrations.AddField(
            model_name='articleorigin',
            name='farm_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.farmshop'),
        ),
        migrations.AddField(
            model_name='customer',
            name='farm_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.farmshop'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='farm_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.farmshop'),
        ),
        migrations.AddField(
            model_name='order',
            name='farm_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.farmshop'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='farm_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.farmshop'),
        ),
        migrations.AddField(
            model_name='package',
            name='farm_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.farmshop'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='farm_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.farmshop'),
        ),
    ]
