# Generated by Django 4.2.16 on 2024-09-23 12:57

from django.db import migrations, models
import farmshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0006_farmshop_article_farm_shop_articleorigin_farm_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmshop',
            name='farmshop_logo',
            field=models.ImageField(blank=True, help_text='Graphik mit Logo', null=True, upload_to=farmshop.models.FarmShop.get_upload_path, verbose_name='Logo'),
        ),
    ]
