# Generated by Django 4.2.16 on 2024-09-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0007_farmshop_farmshop_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleorigin',
            name='description',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Produktgruppenbeschreibung'),
        ),
        migrations.AlterField(
            model_name='articleorigin',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Produktgruppe'),
        ),
    ]
