# Generated by Django 4.2.16 on 2024-09-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0008_articleorigin_description_alter_articleorigin_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='farm_shop',
            new_name='farmshop',
        ),
        migrations.RenameField(
            model_name='articleorigin',
            old_name='farm_shop',
            new_name='farmshop',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='farm_shop',
            new_name='farmshop',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='farm_shop',
            new_name='farmshop',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='farm_shop',
            new_name='farmshop',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='farm_shop',
            new_name='farmshop',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='farm_shop',
            new_name='farmshop',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='farm_shop',
            new_name='farmshop',
        ),
    ]
