# Generated by Django 4.2.16 on 2024-09-30 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmshop', '0010_alter_package_article_alter_package_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('title', models.CharField(max_length=300, verbose_name='Produktbezeichnung')),
                ('description', models.CharField(max_length=4096, verbose_name='Produktbeschreibung')),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Steuersatz')),
                ('farmshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.farmshop')),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='package',
            name='article',
        ),
        migrations.RenameModel(
            old_name='ArticleOrigin',
            new_name='ProductGroup',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='product',
            name='produkt_group',
            field=models.ForeignKey(help_text='Herkunft', on_delete=django.db.models.deletion.CASCADE, to='farmshop.productgroup', verbose_name='Herkunft'),
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ForeignKey(help_text='Hilfe zum Produkt', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.product', verbose_name='Produkt'),
        ),
    ]
