# Generated by Django 4.2.16 on 2024-09-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0011_product_remove_package_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='produkt_group',
            new_name='product_group',
        ),
    ]
