# Generated by Django 4.2.16 on 2024-09-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0012_rename_produkt_group_product_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='shop_quota',
            field=models.IntegerField(default=0, help_text='Maximal online bestellbare Menge', verbose_name='Online Kontingent'),
        ),
    ]
