# Generated by Django 4.2.16 on 2024-09-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0014_remove_package_shop_quota_inventory_online_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='unit_type',
            field=models.CharField(choices=[('KGM', 'Kilogramm'), ('H87', 'Stück'), ('C62', 'ein'), ('MTK', 'Quadratmeter'), ('LM', 'Laufende Meter')], default='H87', max_length=5, verbose_name='Einheit'),
            preserve_default=False,
        ),
    ]
