# Generated by Django 4.2.16 on 2024-09-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0016_rename_unit_type_package_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
