# Generated by Django 4.2.16 on 2024-09-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0017_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notice',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Anmerkungen'),
        ),
    ]
