# Generated by Django 4.2.16 on 2024-09-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0018_order_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
