# Generated by Django 4.2.16 on 2024-10-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0019_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Kunde', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.customer', verbose_name='Kunde'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='package',
            field=models.ForeignKey(help_text='Packung', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='farmshop.package', verbose_name='Packung'),
        ),
        migrations.AlterField(
            model_name='order',
            name='target_date',
            field=models.DateField(verbose_name='Abholdatum'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(help_text='Bestellung', on_delete=django.db.models.deletion.CASCADE, related_name='has_lines', to='farmshop.order', verbose_name='Bestellung'),
        ),
    ]
