# Generated by Django 4.2.16 on 2024-10-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0020_order_customer_alter_inventory_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Nach der Stornierung kann die Bestellung nicht mehr bearbeitet werden. Die Informationen werden verworfen.', verbose_name='Stornieren'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Nach der Bestätigung kann die Bestellung nicht mehr bearbeitet werden. Bitte stornieren Sie sie, wenn sie Fehler enthält.', verbose_name='Bestätigen'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(help_text='Bestellung', on_delete=django.db.models.deletion.CASCADE, to='farmshop.order', verbose_name='Bestellung'),
        ),
    ]
