# Generated by Django 4.2.16 on 2024-10-15 06:28

from django.db import migrations, models
import farmshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0021_order_cancelled_order_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='image',
            field=models.ImageField(blank=True, help_text='Beispielbild', null=True, upload_to=farmshop.models.ProductGroup.get_upload_path, verbose_name='Bild'),
        ),
    ]
