# Generated by Django 4.2.16 on 2024-10-15 07:08

from django.db import migrations, models
import farmshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0022_productgroup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, help_text='Beispielbild', null=True, upload_to=farmshop.models.Package.get_upload_path, verbose_name='Bild'),
        ),
    ]
