# Generated by Django 4.2.16 on 2024-10-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0024_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='production_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Haltbarkeitsdatum'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Produktionsdatum'),
        ),
    ]
