# Generated by Django 4.2.16 on 2024-10-17 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import farmshop.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmshop', '0025_remove_package_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('street_name', models.CharField(help_text="Beispiel: 'Musterstraße 10'", max_length=300, verbose_name='Strasse und Hausnummer')),
                ('city_name', models.CharField(help_text="Beispiel: 'Musterdorf'", max_length=300, verbose_name='Stadt/Ort')),
                ('postal_zone', models.CharField(help_text="Beispiel: '12345'", max_length=5, validators=[farmshop.models.only_int], verbose_name='Postleitzahl')),
                ('country_subentity', models.CharField(choices=[('RLP', 'Rheinland-Pfalz'), ('HE', 'Hessen')], default='RLP', max_length=128, verbose_name='Bundesland')),
                ('country', models.CharField(max_length=128)),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='farmshop',
            name='party_postal_address',
            field=models.ForeignKey(blank=True, help_text='BT-50 - BT-55', null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.postaladdress', verbose_name='Postalische Adresse'),
        ),
    ]
