# Generated by Django 4.2.16 on 2024-10-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0026_postaladdress_farmshop_party_postal_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmshop',
            old_name='party_postal_address',
            new_name='postal_address',
        ),
    ]
