# Generated by Django 4.2.16 on 2024-10-17 06:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0027_rename_party_postal_address_farmshop_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaladdress',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
