# Generated by Django 4.2.16 on 2024-10-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0030_farmshopnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmshopnews',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publikationsdatum'),
        ),
    ]
