# Generated by Django 4.2.16 on 2024-11-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0032_preorder_preorderpackages_order_preorder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preorderpackages',
            unique_together={('preorder', 'package')},
        ),
    ]
