# Generated by Django 4.2.16 on 2024-11-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0033_alter_preorderpackages_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmshopnews',
            name='test',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='preorderpackages',
            name='max_packages',
            field=models.IntegerField(default=1, verbose_name='Maximale Packungen'),
        ),
    ]
