# Generated by Django 4.2.16 on 2024-11-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0034_farmshopnews_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmshopnews',
            name='test',
        ),
    ]
