# Generated by Django 4.2.16 on 2024-11-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0035_remove_farmshopnews_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorderpackages',
            old_name='max_packages',
            new_name='max_packages4',
        ),
    ]
