# Generated by Django 4.2.16 on 2024-11-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0036_rename_max_packages_preorderpackages_max_packages4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorderpackages',
            old_name='max_packages4',
            new_name='max_packages',
        ),
    ]
