# Generated by Django 4.2.16 on 2024-12-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0037_rename_max_packages4_preorderpackages_max_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='max_packages',
            field=models.IntegerField(default=1, verbose_name='Maximal bestellbare Packungen'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmshop.package', verbose_name='Packung/Paket'),
        ),
    ]
