# Generated by Django 4.2.16 on 2024-12-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0038_preorder_max_packages_preorder_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreOrderPackages',
        ),
    ]
