# Generated by Django 4.2.13 on 2025-06-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0039_delete_preorderpackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmshop',
            name='impressum',
            field=models.TextField(blank=True, null=True, verbose_name='Impressum Hofladen'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='farmshop',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='farmshopinfo',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='farmshopnews',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Nach der Stornierung kann die Bestellung nicht mehr bearbeitet werden. Die Informationen werden verworfen.', verbose_name='Storniert'),
        ),
        migrations.AlterField(
            model_name='order',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Nach der Bestätigung kann die Bestellung nicht mehr bearbeitet werden. Bitte stornieren Sie sie, wenn sie Fehler enthält.', verbose_name='Bestätigt'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='package',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzte Änderung'),
        ),
    ]
