# Generated by Django 4.2.13 on 2025-06-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0040_farmshop_impressum_alter_customer_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmshop',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Kontakttelefon für Anfragen'),
        ),
    ]
