# Generated by Django 4.2.13 on 2025-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0041_farmshop_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmshop',
            name='css_style',
            field=models.TextField(blank=True, null=True, verbose_name='CSS-Style für Seite'),
        ),
    ]
