# Generated by Django 4.2.13 on 2025-06-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0042_farmshop_css_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='picked_up',
            field=models.BooleanField(default=False, help_text='Vorbestellung wurde abgeholt', verbose_name='Abgeholt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='preorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='farmshop.preorder', verbose_name='Vorbestellung'),
        ),
    ]
