# Generated by Django 4.2.13 on 2025-06-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0043_preorder_picked_up_alter_order_preorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='picked_up',
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up',
            field=models.BooleanField(default=False, help_text='Bestellung wurde abgeholt', verbose_name='Abgeholt'),
        ),
    ]
