# Generated by Django 4.2.13 on 2025-06-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0044_remove_preorder_picked_up_order_picked_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='EMail-Adresse *', max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(help_text='Vorname *', max_length=300, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Nachname *', max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Telefonnummer *', max_length=300, verbose_name='Telefonnummer'),
        ),
    ]
