# Generated by Django 4.2.13 on 2025-06-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0045_alter_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='target_date',
            field=models.DateField(blank=True, null=True, verbose_name='Abholdatum'),
        ),
    ]
