# Generated by Django 4.2.13 on 2025-06-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0046_alter_order_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, help_text='Vorname', max_length=300, null=True, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefonnummer', max_length=300, null=True, verbose_name='Telefonnummer'),
        ),
    ]
