# Generated by Django 4.2.13 on 2025-07-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmshop', '0047_alter_customer_first_name_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmshop',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Kontakt E-Mail*', max_length=254, null=True, verbose_name='E-Mail'),
        ),
    ]
